# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 10:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonmodel',
            name='roles',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='jsonmodel',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'html': '<h1>Default</h1>', 'status': False, 'text': 'some text'}),
        ),
    ]
