# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 13:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrayJSONModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.AlterField(
            model_name='jsonmodel',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'html': '<h1>Default</h1>', 'status': False, 'text': 'some text'}),
        ),
    ]
