# Generated by Django 2.1.3 on 2018-12-05 08:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherJSONModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={'other_text': 'some other text', 'status': True})),
            ],
        ),
        migrations.CreateModel(
            name='RelatedJSONModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_data', django.contrib.postgres.fields.jsonb.JSONField(default={'related_info': '', 'relevant': False})),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OtherJSONModel')),
            ],
        ),
    ]
